export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Link from "next/link";
import "../globals.css";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <span className="h-[30px] flex bg-neutral-400/20  shadow-lg justify-center">
          {" "}
          <Link className="text-xl" href={"/"}>
            На головну
          </Link>
        </span>
        {children}
      </body>
    </html>
  );
}
